### ISSUE TITLE
Port over original dash app and jupyter notebook 

### ISSUE THREAD

**Issue by Tachikoma000** [0xPlaygrounds/playgrounds#2]
Commit the newest and working version of playgrounds dash app to this repo for Marcus 
- [ ] Check that all libraries are called
- [ ] Make sure requirements.txt file is included
- [ ] Test the app on local machine and rectify any broken code
- [ ] Make sure to include documentation file as well

**Comment by 0xAurelius** [comment]
Initial port has been done (except for "Explore" view w/ Subgraph integration), now we just need to componentize
